default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  username: admin
  password: GOROgoro440!
  host: database-1.ctgoawsygoy7.ap-northeast-1.rds.amazonaws.com
  pool: 5
  timeout: 5000

production:
  primary:
    <<: *default
    database: Livais_dev_db_1
  queue:
    <<: *default
    database: Livais_queue_db
  cache:
    <<: *default
    database: Livais_cache_db
  cable:
    <<: *default
    database: Livais_cable_db
