# Workflowの名前。任意に設定可能
name: deploy to dev

# アクションが実行されるタイミングを設定。今回はdevブランチにpushされた時。
on:
 push:
   branches:
     - dev
 
#実行される処理
jobs:
 build:
   # 実行環境の指定
   runs-on: ubuntu-latest
   environment: 
     name: AWS
   steps:
     # デプロイする
     - name: Deploy
       env: 
         USER_NAME: ${{ secrets.USER_NAME }}
         HOST_NAME: ${{ secrets.HOST_NAME }}
       run: |
         # SSH接続して、git pullする
         echo "${{ secrets.PRIVATE_KEY }}" > private_key
         chmod 600 private_key
         trap "rm -f private_key" EXIT
         ssh -i private_key -o StrictHostKeyChecking=no $USER_NAME@$HOST_NAME "cd /var/www/Livais-backend && git pull git@github.com:doguto/Livais-backend.git && RAILS_ENV=production rails db:migrate"
       shell: bash
